# numpy

In [1]:
import numpy

* 查看numpy的版本

In [2]:
numpy.__version__

'1.13.3'

In [3]:
import numpy as np

In [4]:
np.__version__


'1.13.3'

## Python List 的特点

In [6]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
L[5]

5

In [9]:
L[5] = 100
L


[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

## python List比较灵活，可以list中可以有多种类型
* 所以需要在识别list的过程中识别每一个元素的数据类型，操作的速度较慢

In [12]:
L[5] = 'Machine Learning'
L

[0, 1, 2, 3, 4, 'Machine Learning', 6, 7, 8, 9]

* 使用array，array中的元素只运行是同一种的元素

In [13]:
import array

In [14]:
arr = array.array('i', [i for i in range(10)])

In [15]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr[5] = 100
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

* 将array中的一个元素赋值为其它类型的数据类型，将会报错

In [18]:
arr[5] = 'machine learing'

TypeError: an integer is required (got type str)

## numpy.array
* 以下同array的性质相似

In [19]:
nparr  = np.array([i for i in range(10)])

In [20]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
nparr[5] = 100

In [22]:
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [23]:
nparr[5]  = 'r'

ValueError: invalid literal for int() with base 10: 'r'

In [24]:
nparr.dtype

dtype('int32')

In [29]:
nparr[5] = 3.14

* 进行了隐式的数据转换

In [27]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 其它创建numpy.array的方法
* zeros方法生成元素为0的矩阵
- ones方法生成全为1的矩阵
- full方法可以进行填充一个值

In [32]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [33]:
np.zeros(10).dtype

dtype('float64')

In [34]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [37]:
np.zeros((3,5), dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [38]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [40]:
np.ones((3,5), dtype =int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [41]:
np.full((3,5), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [42]:
np.full(shape=(3,5), fill_value=10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

## arange
* 功能类似于range，生成一个范围内的有一定步长的数组
* 但不同于range的是，在该方法中可以使用浮点型的数据作为输入

In [44]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [45]:
np.arange(0, 1, 0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

## linspace

In [46]:
np.linspace(0, 20, 10)
# 生成0-20之间的等差数列，10个数，包含0和20

array([  0.        ,   2.22222222,   4.44444444,   6.66666667,
         8.88888889,  11.11111111,  13.33333333,  15.55555556,
        17.77777778,  20.        ])

In [47]:
np.linspace(0, 20, 11)

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.])

## random

In [50]:
np.random.randint(0, 10, size = 10)

array([8, 3, 9, 6, 3, 7, 1, 6, 8, 3])

* 因为用到的随机数都是伪随机数，所以在设定随机数种子之后，两次随机生成的数组是一样的

In [53]:
np.random.seed(1000)
np.random.randint(0, 10, size = 10)

array([3, 7, 7, 0, 1, 0, 9, 8, 9, 4])

In [54]:
np.random.seed(1000)
np.random.randint(0, 10, size = 10)

array([3, 7, 7, 0, 1, 0, 9, 8, 9, 4])

In [55]:
np.random.random()

0.8517471987138742

In [56]:
np.random.random(10)

array([ 0.57432043,  0.77250273,  0.9066506 ,  0.06032431,  0.02119571,
        0.90500709,  0.81729934,  0.08585602,  0.85544031,  0.24453192])

In [57]:
np.random.random((2,2))

array([[ 0.65856221,  0.47657574],
       [ 0.81632509,  0.24071122]])

### nomal 生成指定均值，和方差的随机数

In [66]:
np.random.normal(loc=10,scale=100,size=10)

array([  37.77283981,   47.68117189,   18.13379194,  101.54615495,
         99.89578633,  -15.43312193,   24.73978704,  -54.9984287 ,
         70.59846046,  127.26178163])

* 在命令后面加上？可以看到产生文档所需要的参数

In [67]:
np.random.normal?